name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit Test on Node ${{matrix.node_version}} (${{matrix.os}}) and GraphQL v${{matrix.graphql_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{matrix.node_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
